# Generated by Django 5.2.4 on 2025-07-06 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_listing_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
